name: Build and Deploy Monorepo

on:
  push:
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build backend
        working-directory: ./backend
        run: ./gradlew build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend/build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ./frontend-dist

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: ./backend-build

      - name: Build Docker image
        run: docker build -t my-app-image .
